services:
  geth-for-codex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
      - 30303:30303
    environment:
      - GETH_ARGS=--http --http.addr 0.0.0.0
      - UNLOCK_START_INDEX=0
      - UNLOCK_NUMBER=1
      - ENABLE_MINER=1
      - NAT_PUBLIC_IP_AUTO=ip.codex.storage
